; Foto menu & nota dari HP bisa beberapa MB
upload_max_filesize = 10M
post_max_size = 12M
memory_limit = 256M
expose_php = Off
date.timezone = Asia/Makassar

opcache.enable = 1
opcache.memory_consumption = 64
opcache.validate_timestamps = 0
